######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 16 00:40:02 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . GeneratedFiles
INCLUDEPATH += .

QT += network \
   += gui \
   += core \
   += sql

# Input
HEADERS += clientsocket.h constant.h database.h server.h widget.h
SOURCES += clientSocket.cpp database.cpp main.cpp server.cpp widget.cpp
